---
services:
  data-prepper:
    restart: unless-stopped
    container_name: data-prepper
    image: opensearchproject/data-prepper:2
    volumes:
      # - ./configs/trace_analytics_no_ssl_2x.yml:/usr/share/data-prepper/pipelines/pipelines.yaml
      # - ./configs/trace_analytics_no_ssl_2x_with_metrics_and_logs.yml:/usr/share/data-prepper/pipelines/pipelines.yaml
      - ./configs/trace_analytics_no_ssl_2x_with_metrics.yml:/usr/share/data-prepper/pipelines/pipelines.yaml
      - ./configs/data-prepper-config.yaml:/usr/share/data-prepper/config/data-prepper-config.yaml
      - ./configs/root-ca.pem:/usr/share/data-prepper/root-ca.pem
    ports:
      - "21890:21890"
      - "21891:21891"
      - "2021:2021"
    depends_on:
      opensearch:
        condition: service_healthy
    mem_limit: 256m
  opensearch:
    container_name: node-0.example.com
    image: opensearchproject/opensearch:2
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    mem_limit: 1.5g
    healthcheck:
      test: curl -i --insecure -XGET https://localhost:9200/_cluster/health -u 'admin:admin' | grep -E '("status":"yellow"|"status":"green")'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  dashboards:
    image: opensearchproject/opensearch-dashboards:2
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://node-0.example.com:9200"]'
    depends_on:
      opensearch:
        condition: service_healthy
    mem_limit: 512m
  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:8.4.0
    container_name: logstash
    mem_limit: 1.5g
    volumes:
      # - ./configs/logstash.conf:/usr/share/logstash/config/logstash.conf
      - ./configs/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - 5044:5044
    depends_on:
      opensearch:
        condition: service_healthy
      init:
        condition: service_completed_successfully
    healthcheck:
      test:  curl -XGET 'localhost:9600/?pretty'
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:8.6.1
    user: root
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./configs/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    command: [ "--strict.perms=false" ]
    depends_on:
    #   data-prepper:
    #     condition: service_healthy
      logstash:
        condition: service_healthy
      init:
        condition: service_completed_successfully
    # restart: always
    mem_limit: 512m
  init:
    image: hashicorp/terraform
    container_name: init
    working_dir: /workspace
    # command: ["apply", "-auto-approve"]
    entrypoint: /init_entrypoint.sh
    depends_on:
      opensearch:
        condition: service_healthy
    volumes:
      - ./configs/init_entrypoint.sh:/init_entrypoint.sh:ro
    # restart: always
