---
apiVersion: v1
kind: ConfigMap
metadata:
  name: data-prepper-configs
data:
  data-prepper-config.yaml: |
    ---
    ssl: false
  pipelines.yaml: |
    entry-pipeline:
        delay: "100"
        source:
            otel_trace_source:
            ssl: false
            port: 21890
        sink:
            - pipeline:
                name: "raw-pipeline"
            - pipeline:
                name: "service-map-pipeline"
        raw-pipeline:
        source:
            pipeline:
            name: "entry-pipeline"
        processor:
            - otel_trace_raw:
        sink:
            - opensearch:
                hosts: [ "https://opensearch:9200" ]
                cert: "/usr/share/data-prepper/root-ca.pem"
                username: admin
                password: admin
                index_type: trace-analytics-raw
        service-map-pipeline:
        delay: "100"
        source:
            pipeline:
            name: "entry-pipeline"
        processor:
            - service_map_stateful:
        sink:
            - stdout:
            - opensearch:
                hosts: [ "https://node-0.example.com:9200" ]
                cert: "/usr/share/data-prepper/root-ca.pem"
                username: admin
                password: admin
                index_type: trace-analytics-service-map

        metrics-pipeline:
        source:
            otel_metrics_source:
            ssl: false
            port: 21891
        processor:
            - otel_metrics_raw_processor:
        sink:
            - stdout:
            - opensearch:
                hosts: [ "https://node-0.example.com:9200" ]
                cert: "/usr/share/data-prepper/root-ca.pem"
                username: admin
                password: admin
                index: "metrics-otel-v1-%{yyyy.MM.dd}"
                indexAlias: "metrics-otel-v1"
  root-ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIID/jCCAuagAwIBAgIBATANBgkqhkiG9w0BAQsFADCBjzETMBEGCgmSJomT8ixk
    ARkWA2NvbTEXMBUGCgmSJomT8ixkARkWB2V4YW1wbGUxGTAXBgNVBAoMEEV4YW1w
    bGUgQ29tIEluYy4xITAfBgNVBAsMGEV4YW1wbGUgQ29tIEluYy4gUm9vdCBDQTEh
    MB8GA1UEAwwYRXhhbXBsZSBDb20gSW5jLiBSb290IENBMB4XDTE4MDQyMjAzNDM0
    NloXDTI4MDQxOTAzNDM0NlowgY8xEzARBgoJkiaJk/IsZAEZFgNjb20xFzAVBgoJ
    kiaJk/IsZAEZFgdleGFtcGxlMRkwFwYDVQQKDBBFeGFtcGxlIENvbSBJbmMuMSEw
    HwYDVQQLDBhFeGFtcGxlIENvbSBJbmMuIFJvb3QgQ0ExITAfBgNVBAMMGEV4YW1w
    bGUgQ29tIEluYy4gUm9vdCBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
    ggEBAK/u+GARP5innhpXK0c0q7s1Su1VTEaIgmZr8VWI6S8amf5cU3ktV7WT9SuV
    TsAm2i2A5P+Ctw7iZkfnHWlsC3HhPUcd6mvzGZ4moxnamM7r+a9otRp3owYoGStX
    ylVTQusAjbq9do8CMV4hcBTepCd+0w0v4h6UlXU8xjhj1xeUIz4DKbRgf36q0rv4
    VIX46X72rMJSETKOSxuwLkov1ZOVbfSlPaygXIxqsHVlj1iMkYRbQmaTib6XWHKf
    MibDaqDejOhukkCjzpptGZOPFQ8002UtTTNv1TiaKxkjMQJNwz6jfZ53ws3fh1I0
    RWT6WfM4oeFRFnyFRmc4uYTUgAkCAwEAAaNjMGEwDwYDVR0TAQH/BAUwAwEB/zAf
    BgNVHSMEGDAWgBSSNQzgDx4rRfZNOfN7X6LmEpdAczAdBgNVHQ4EFgQUkjUM4A8e
    K0X2TTnze1+i5hKXQHMwDgYDVR0PAQH/BAQDAgGGMA0GCSqGSIb3DQEBCwUAA4IB
    AQBoQHvwsR34hGO2m8qVR9nQ5Klo5HYPyd6ySKNcT36OZ4AQfaCGsk+SecTi35QF
    RHL3g2qffED4tKR0RBNGQSgiLavmHGCh3YpDupKq2xhhEeS9oBmQzxanFwWFod4T
    nnsG2cCejyR9WXoRzHisw0KJWeuNlwjUdJY0xnn16srm1zL/M/f0PvCyh9HU1mF1
    ivnOSqbDD2Z7JSGyckgKad1Omsg/rr5XYtCeyJeXUPcmpeX6erWJJNTUh6yWC/hY
    G/dFC4xrJhfXwz6Z0ytUygJO32bJG4Np2iGAwvvgI9EfxzEv/KP+FGrJOvQJAq4/
    BU36ZAa80W/8TBnqZTkNnqZV
    -----END CERTIFICATE-----
