---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: eldius/opensearch-postgres:2.1.1
          ports:
            - containerPort: 21890
            - containerPort: 21891
            - containerPort: 2021
          resources:
            limits:
              memory: 256M
            requests:
              memory: 256M
          volumeMounts:
          # - name: root-ca-pem
          #  mountPath: /usr/share/postgres/
          #  readOnly: true
          - name: postgres-config-yaml
            mountPath: /usr/share/postgres/config
            #readOnly: true
          - name: pipelines-yaml
            mountPath: /usr/share/postgres/pipelines
            #readOnly: true
      volumes:
        - name: root-ca-pem
          configMap:
            name: postgres-config-files
            items:
            - key: root-ca.pem
              path: root-ca.pem
        - name: postgres-config-yaml
          configMap:
            name: postgres-config-files
            items:
            - key: postgres-config.yaml
              path: postgres-config.yaml
            - key: log4j2-rolling.properties
              path: log4j2-rolling.properties
        - name: pipelines-yaml
          configMap:
            name: postgres-config-files
            items:
            - key: pipelines.yaml
              path: pipelines.yaml
      restartPolicy: Always
