---
services:
  service_a:
    build: ../rest-service-a
    container_name: service-a
    ports:
      - 8080:8080
    environment:
      - API_LOG_LEVEL="trace"
      - API_OTEL_ENDPOINT="$(OTEL_ENDPOINT)"
      - API_DB_HOST=$(DB_HOST)
      - API_DB_PASS="P@ss"
      - API_TELEMETRY_REST_ENABLE=true
      - API_TELEMETRY_DB_ENABLE=true
    mem_limit: 16m

