---
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "14268:14268"
      - "4317"          # OTLP over gRPC receiver
      - "4318:4318"     # OTLP over HTTP receiver
      - "9464"          # Prometheus exporter
      - "8888"          # metrics endpoint
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    command: "--collector.otlp.grpc.host-port \":4317\""
    mem_limit: 512m
    healthcheck:
      test: wget --spider http://localhost:16686/ || exit 1
      interval: 10s
      retries: 10
      timeout: 5s
