# version: '2.4'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    container_name: elasticsearch
    labels:
      co.elastic.logs/module: elasticsearch
      co.elastic.logs/fileset.stdout: access
      co.elastic.logs/fileset.stderr: error
    environment:
      - bootstrap.memory_lock=true
      - cluster.name=docker-cluster
      - cluster.routing.allocation.disk.threshold_enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-XX:UseAVX=2 -Xms1g -Xmx1g
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.enabled=$ELASTIC_SECURITY
    ulimits:
      memlock:
        hard: -1
        soft: -1
    ports:
      - 9200:9200
    mem_limit: 1.5g
    volumes:
      - ./config/elasticsearch_entrypoint.sh:/usr/local/bin/docker-entrypoint-alt.sh:ro
    #   - ./config/setup_kibana_user.sh:/usr/local/bin/setup_kibana_user.sh:ro
    #   - ./config/elasticsearch_entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:ro
    entrypoint: ["/usr/local/bin/docker-entrypoint-alt.sh"]
    healthcheck:
      interval: 10s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"Server available"'

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
    container_name: kibana
    environment:
      - ELASTIC_USERNAME=$ELASTIC_USERNAME
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD

    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    mem_limit: 1g
    healthcheck:
      interval: 10s
      retries: 10
      test: curl -i -u ${ELASTIC_USERNAME}:${ELASTIC_PASSWORD}  "http://127.0.0.1:5601/api/status" | grep -q '"state":"green"'

  terraform:
    image: hashicorp/terraform
    container_name: terraform
    environment:
      - ELASTICSEARCH_USERNAME=$ELASTIC_USERNAME
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - ELASTICSEARCH_URL=elasticsearch:9200
      - KIBANA_URL=kibana:5601
      - ELASTICSEARCH_HEALTH=false
      # - TF_LOG_PROVIDER=TRACE
    working_dir: /workspace
    # command: ["apply", "-auto-approve"]
    entrypoint: /terraform_entrypoint.sh
    depends_on:
      kibana:
        condition: service_healthy
    volumes:
      - ../terraform/:/workspace
      - ./config/terraform_entrypoint.sh:/terraform_entrypoint.sh:ro
    # restart: always

  filebeat:
    container_name: filebeat
    hostname: "metricbeat"
    image: docker.elastic.co/beats/filebeat:${ELK_VERSION}
    user: root
    mem_limit: 512m
    environment:
      - ELASTIC_USERNAME=$ELASTIC_USERNAME
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    command: [ "--strict.perms=false", "-system.hostfs=/hostfs" ]
    depends_on:
      kibana:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      terraform:
        condition: service_completed_successfully
    # restart: always
    cpu_count: 1
