---
filebeat.autodiscover:
  providers:
    - type: docker
      condition:
        not:
          regexp:
            docker.container.name: "(opensearch|logstash|filebeat)"
      templates:
        - config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log

processors:
  - add_cloud_metadata: ~



output.logstash:
  hosts: ["logstash:5044"]


logging:
  # level: debug
  level: info
  to_files: true
  files:
    path: /var/log/filebeat
    name: filebeat.log
    keepfiles: 7
    permissions: 0640
