apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -v --file docker-compose-opensearch.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: opensearch
  name: opensearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: opensearch
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -v --file docker-compose-opensearch.yml convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: opensearch
    spec:
      containers:
        - env:
            - name: OPENSEARCH_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: bootstrap.memory_lock
              value: "true"
            - name: discovery.type
              value: single-node
          image: opensearchproject/opensearch:2
          livenessProbe:
            exec:
              command:
                - curl -i --insecure -XGET https://localhost:9200/_cluster/health -u 'admin:admin' | grep -E '("status":"yellow"|"status":"green")'
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          name: opensearch
          ports:
            - containerPort: 9200
            - containerPort: 9600
          resources:
            limits:
              memory: 2G
            requests:
              memory: 1.5G
      restartPolicy: Always
status: {}
