---
filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log

processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: "${ELASTICSEARCH_HOSTS:elasticsearch:9200}"
  username: "${ELASTIC_USERNAME:}"
  password: "${ELASTIC_PASSWORD:}"
  enabled: true
  index: filebeat-7.15.2-2023.02.02-000001

setup.template:
  name: 'filebeat'
  pattern: "filebeat-7.15.2-*"
  overwrite: false
  enabled: false

setup.dashboards.enabled: false

logging:
  # level: debug
  level: info
  to_files: true
  files:
    path: /var/log/filebeat
    name: filebeat.log
    keepfiles: 7
    permissions: 0640
